spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/quickly
    username: quickly
    password: quickly
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        default_schema: catalog
  flyway:
    enabled: true
    schemas: catalog
    locations: classpath:db/migration

logging:
  level:
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: INFO
